// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm18slB0VPx6BWFjuIxnGj7oL3rxZLV_M',
    appId: '1:541819071184:web:e8138d6586fdd61943ccd5',
    messagingSenderId: '541819071184',
    projectId: 'flutter-task-test-5bff9',
    authDomain: 'flutter-task-test-5bff9.firebaseapp.com',
    storageBucket: 'flutter-task-test-5bff9.appspot.com',
    measurementId: 'G-9J569WEB0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXGxmmbkUPvdOOxyj6aoPjy2uF5ZPSz_U',
    appId: '1:541819071184:android:b5d3b9795d0b2bf143ccd5',
    messagingSenderId: '541819071184',
    projectId: 'flutter-task-test-5bff9',
    storageBucket: 'flutter-task-test-5bff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjaH6SsUoX41ofpqdkCb-h7J0ltb3CrMo',
    appId: '1:541819071184:ios:79d86ef45a49dafb43ccd5',
    messagingSenderId: '541819071184',
    projectId: 'flutter-task-test-5bff9',
    storageBucket: 'flutter-task-test-5bff9.appspot.com',
    iosClientId: '541819071184-90s2ng2e3848ppg0v90d330p7g4js7rv.apps.googleusercontent.com',
    iosBundleId: 'com.csolg.flutter.test',
  );
}
